-- PRD v2.0 - Marolo App
-- Modo single-team consultivo:
-- - admin edita
-- - jogador apenas consulta

create extension if not exists pgcrypto;

-- =====================================================
-- Tabelas (devem existir antes das funções que as referenciam)
-- =====================================================
create table if not exists public.perfis (
  id int8 primary key generated by default as identity,
  usuario_id uuid not null unique references auth.users(id) on delete cascade,
  nome_time text not null,
  slug text not null unique,
  descricao text,
  logo_url text,
  configuracao_tema jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.jogadores (
  id int8 primary key generated by default as identity,
  perfil_id int8 not null references public.perfis(id) on delete cascade,
  nome text not null,
  posicao text,
  numero_camisa int2,
  avatar_url text,
  data_nascimento date,
  telefone text,
  email text,
  tags jsonb,
  ativo bool default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (perfil_id, email)
);

create table if not exists public.jogos (
  id int8 primary key generated by default as identity,
  perfil_id int8 not null references public.perfis(id) on delete cascade,
  data_hora timestamptz not null,
  adversario text not null,
  local text,
  resultado jsonb,
  formacao text,
  notas text,
  status text default 'agendado',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.presencas (
  id int8 primary key generated by default as identity,
  jogo_id int8 not null references public.jogos(id) on delete cascade,
  jogador_id int8 not null references public.jogadores(id) on delete cascade,
  presente bool default true,
  gols int2 default 0,
  assistencias int2 default 0,
  cartoes jsonb,
  notas text,
  avaliacao int2,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (jogo_id, jogador_id)
);

create table if not exists public.caixa (
  id int8 primary key generated by default as identity,
  perfil_id int8 not null references public.perfis(id) on delete cascade,
  tipo text not null,
  categoria text,
  descricao text not null,
  valor numeric(10, 2) not null,
  data_movimento date not null,
  metodo_pagamento text,
  comprovante_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.pagamentos (
  id int8 primary key generated by default as identity,
  perfil_id int8 not null references public.perfis(id) on delete cascade,
  jogador_id int8 not null references public.jogadores(id) on delete cascade,
  mes int2 not null,
  ano int2 not null,
  valor numeric(10, 2) not null default 100.00,
  status text default 'pendente',
  data_vencimento date,
  data_pagamento date,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (perfil_id, jogador_id, mes, ano)
);

create table if not exists public.membros (
  id int8 primary key generated by default as identity,
  perfil_id int8 not null references public.perfis(id) on delete cascade,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  papel text default 'jogador',
  created_at timestamptz default now(),
  unique (perfil_id, usuario_id)
);

-- =====================================================
-- Funções (após as tabelas, pois language sql valida referências)
-- =====================================================
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.has_team_access(p_perfil_id bigint)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.perfis p
    where p.id = p_perfil_id
      and (
        p.usuario_id = auth.uid()
        or exists (
          select 1
          from public.membros m
          where m.perfil_id = p.id
            and m.usuario_id = auth.uid()
        )
      )
  );
$$;

create or replace function public.is_team_admin(p_perfil_id bigint)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.perfis p
    where p.id = p_perfil_id
      and (
        p.usuario_id = auth.uid()
        or exists (
          select 1
          from public.membros m
          where m.perfil_id = p.id
            and m.usuario_id = auth.uid()
            and m.papel = 'admin'
        )
      )
  );
$$;

-- =====================================================
-- Triggers
-- =====================================================
drop trigger if exists trg_perfis_updated_at on public.perfis;
create trigger trg_perfis_updated_at before update on public.perfis
for each row execute function public.set_updated_at();

drop trigger if exists trg_jogadores_updated_at on public.jogadores;
create trigger trg_jogadores_updated_at before update on public.jogadores
for each row execute function public.set_updated_at();

drop trigger if exists trg_jogos_updated_at on public.jogos;
create trigger trg_jogos_updated_at before update on public.jogos
for each row execute function public.set_updated_at();

drop trigger if exists trg_presencas_updated_at on public.presencas;
create trigger trg_presencas_updated_at before update on public.presencas
for each row execute function public.set_updated_at();

drop trigger if exists trg_caixa_updated_at on public.caixa;
create trigger trg_caixa_updated_at before update on public.caixa
for each row execute function public.set_updated_at();

drop trigger if exists trg_pagamentos_updated_at on public.pagamentos;
create trigger trg_pagamentos_updated_at before update on public.pagamentos
for each row execute function public.set_updated_at();

-- =====================================================
-- RLS
-- =====================================================
alter table public.perfis enable row level security;
alter table public.jogadores enable row level security;
alter table public.jogos enable row level security;
alter table public.presencas enable row level security;
alter table public.caixa enable row level security;
alter table public.pagamentos enable row level security;
alter table public.membros enable row level security;

-- =====================================================
-- Policies
-- =====================================================
drop policy if exists perfis_read_all on public.perfis;
create policy perfis_read_all on public.perfis
for select using (
  usuario_id = auth.uid()
  or exists (
    select 1
    from public.membros m
    where m.perfil_id = perfis.id
      and m.usuario_id = auth.uid()
  )
);

drop policy if exists perfis_insert_own on public.perfis;
create policy perfis_insert_own on public.perfis
for insert with check (auth.uid() = usuario_id);

drop policy if exists perfis_update_own on public.perfis;
create policy perfis_update_own on public.perfis
for update using (auth.uid() = usuario_id) with check (auth.uid() = usuario_id);

drop policy if exists perfis_delete_own on public.perfis;
create policy perfis_delete_own on public.perfis
for delete using (auth.uid() = usuario_id);

drop policy if exists membros_read_team on public.membros;
create policy membros_read_team on public.membros
for select using (usuario_id = auth.uid());

drop policy if exists membros_insert_owner on public.membros;
create policy membros_insert_owner on public.membros
for insert with check (
  exists (
    select 1
    from public.perfis p
    where p.id = membros.perfil_id
      and p.usuario_id = auth.uid()
  )
);

drop policy if exists membros_update_admin on public.membros;
create policy membros_update_admin on public.membros
for update
using (
  exists (
    select 1
    from public.perfis p
    where p.id = membros.perfil_id
      and p.usuario_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.perfis p
    where p.id = membros.perfil_id
      and p.usuario_id = auth.uid()
  )
);

drop policy if exists membros_delete_admin on public.membros;
create policy membros_delete_admin on public.membros
for delete
using (
  exists (
    select 1
    from public.perfis p
    where p.id = membros.perfil_id
      and p.usuario_id = auth.uid()
  )
);

drop policy if exists jogadores_read_all on public.jogadores;
create policy jogadores_read_all on public.jogadores
for select using (public.has_team_access(perfil_id));

drop policy if exists jogadores_modify_owner on public.jogadores;
create policy jogadores_modify_owner on public.jogadores
for all using (public.is_team_admin(perfil_id)) with check (public.is_team_admin(perfil_id));

drop policy if exists jogos_read_all on public.jogos;
create policy jogos_read_all on public.jogos
for select using (public.has_team_access(perfil_id));

drop policy if exists jogos_modify_owner on public.jogos;
create policy jogos_modify_owner on public.jogos
for all using (public.is_team_admin(perfil_id)) with check (public.is_team_admin(perfil_id));

drop policy if exists caixa_read_all on public.caixa;
create policy caixa_read_all on public.caixa
for select using (public.has_team_access(perfil_id));

drop policy if exists caixa_modify_owner on public.caixa;
create policy caixa_modify_owner on public.caixa
for all using (public.is_team_admin(perfil_id)) with check (public.is_team_admin(perfil_id));

drop policy if exists pagamentos_read_all on public.pagamentos;
create policy pagamentos_read_all on public.pagamentos
for select using (public.has_team_access(perfil_id));

drop policy if exists pagamentos_modify_owner on public.pagamentos;
create policy pagamentos_modify_owner on public.pagamentos
for all using (public.is_team_admin(perfil_id)) with check (public.is_team_admin(perfil_id));

drop policy if exists presencas_read_all on public.presencas;
create policy presencas_read_all on public.presencas
for select using (
  exists (
    select 1 from public.jogos j
    where j.id = presencas.jogo_id
      and public.has_team_access(j.perfil_id)
  )
);

drop policy if exists presencas_modify_owner on public.presencas;
create policy presencas_modify_owner on public.presencas
for all using (
  exists (
    select 1 from public.jogos j
    where j.id = presencas.jogo_id
      and public.is_team_admin(j.perfil_id)
  )
)
with check (
  exists (
    select 1 from public.jogos j
    where j.id = presencas.jogo_id
      and public.is_team_admin(j.perfil_id)
  )
);

-- =====================================================
-- Indices
-- =====================================================
create index if not exists idx_jogadores_perfil on public.jogadores(perfil_id);
create index if not exists idx_jogos_perfil_data on public.jogos(perfil_id, data_hora);
create index if not exists idx_presencas_jogo on public.presencas(jogo_id);
create index if not exists idx_pagamentos_perfil_mes_ano on public.pagamentos(perfil_id, mes, ano);
create index if not exists idx_caixa_perfil_data on public.caixa(perfil_id, data_movimento desc);

-- =====================================================
-- Grants (necessário no Supabase CLI local — o cloud aplica automaticamente)
-- =====================================================
grant usage on schema public to anon, authenticated, service_role;

grant select, insert, update, delete on public.perfis    to anon, authenticated, service_role;
grant select, insert, update, delete on public.jogadores to anon, authenticated, service_role;
grant select, insert, update, delete on public.jogos     to anon, authenticated, service_role;
grant select, insert, update, delete on public.presencas to anon, authenticated, service_role;
grant select, insert, update, delete on public.caixa     to anon, authenticated, service_role;
grant select, insert, update, delete on public.pagamentos to anon, authenticated, service_role;
grant select, insert, update, delete on public.membros   to anon, authenticated, service_role;

grant usage, select on all sequences in schema public to anon, authenticated, service_role;
